### ISSUE TITLE
Outdated regex matching for latest unifi firmware log messages

### ISSUE THREAD

**Issue by ghost** [Graylog2/graylog-guide-ubiquity-unify-ap#2]
On newest stable candidate controller version 5.9.29 and beta firmware 4.0.1.9421 I can't get the logging filter to work. I am able to get logs to show up under system > input.

The guide needs to be updated with newest log syntax:

`U7PG2,f09fc226cf74,v4.0.1.9421: hostapd: ath5: STA aa:bb:cc:dd:ee:ff IEEE 802.11: deauthenticated due to local deauth request`

Currently it only matches logs for the unifi switch
`("US24,f09fc20fd52c,v4.0.1.9421") switch: DOT1S: Port (1) inst(0) role changing from ROLE_DISABLED to ROLE_DESIGNATED`

Thanks

Please update the doc.

**Comment by ghost** [comment]
I have tried messing with the regex a little bit
edit: this works
`^.+,(.+?),.+? (.+?): (.+)$`

**Comment by owentl** [comment]
I changed the regex as well to pull more info out.  I also created a lookup table that has AP mac to common name so I could set the source name.  Not sure it will help anyone but here is my full rule:

rule "parse Ubiquiti access point logs"
when
  has_field("message")
then
  let m = regex("^(.+),(.+?),(.+?): hostapd: (.+?): (.+?) (.+?) (.+): (.+)$", to_string($message.message));
  
  let sname = m["0"];
  let lookupsource = m["1"];
  let version = m["2"];
  let bssid = m["5"];
  let subsystem = m["6"];
  let action = m["7"];
  //let clean_message = m["2"];
  
  // Build a better source name
  //set_field("source", concat("ap-", to_string(bssid)));
  
  // Set additional fields.
  set_field("type", "ubiquity-ap");
  set_field("bssid", bssid);
  set_field("subsystem", subsystem);
  set_field("version",version);
  set_field("sname", sname);
  set_field("action", action);
  
  let lookupsource = lookup("ubnt_lookup",lookupsource);
  set_field("source",lookupsource);

  // Set a better message field without the prefix clutter.
  //set_field("message", clean_message);
end

**Comment by a-oneil** [comment]
> 
> 
> I have tried messing with the regex a little bit
> edit: this works
> `^.+,(.+?),.+? (.+?): (.+)$`

What are you using for your pipeline rules? I can't seem to get the pipeline to work.

**Comment by nessor** [comment]
Seems that this expression is also outdated. Works for me for APs logs, not for USG logs.

**Comment by MoonDogg** [comment]
I changed the regex in the pipeline rule and it works (sorta), and it shows it processing , and works in the simulator but is not changing the message when you do a search..... here is the rule as I have it. 


rule "parse Ubiquity access point logs"
when
  has_field("message")
then
  let m = regex("^.+,(.+?),.+? (.+?): (.+)$", to_string($message.message));
  
  let bssid = m["0"];
  let subsystem = m["1"];
  let clean_message = m["2"];
  
  // Build a better source name
  set_field("source", concat("ap-", to_string(bssid)));
  
  // Set additional fields.
  set_field("type", "ubiquity-ap");
  set_field("bssid", bssid);
  set_field("subsystem", subsystem); 

  // Set a better message field without the prefix clutter.
  set_field("message", clean_message);
end

**Comment by RedVortex** [comment]
> I changed the regex in the pipeline rule and it works (sorta), and it shows it processing , and works in the simulator but is not changing the message when you do a search..... here is the rule as I have it.

Look here: https://github.com/Graylog2/graylog-guide-ubiquity-unify-ap/issues/1

It's because of the order of Message Processors Configuration in Systems/Configurations in graylog. Bottom line, you need to flip the last two options so that Message Filter Chain goes AFTER Pipeline Processor. Thanks @dotsam for finding this.

**Comment by johnenxada** [comment]
Is there anyone that can contribute to this one and update the regex and pipelines so that we can get proper logging to Graylog? Unfortunately my knowledge on this one is limited.
